### ISSUE TITLE
Page not found errors produce trail

### ISSUE THREAD

**Issue by Browne** [not-so-creative/eisenhower#22]
A user searching for /something is presented with a trail rather than an error page. This is because the error page for notFound does not exist.

Trail:
Error: template not found: errors/notFound.html
   at null.<anonymous> (/app/node_modules/nunjucks/src/environment.js:151:31)
   at next (/app/node_modules/nunjucks/src/lib.js:201:13)
   at handle (/app/node_modules/nunjucks/src/environment.js:136:25)
   at /app/node_modules/nunjucks/src/environment.js:147:21
   at next (/app/node_modules/nunjucks/src/lib.js:198:13)
   at Object.exports.asyncIter (/app/node_modules/nunjucks/src/lib.js:205:5)
   at Obj.extend.getTemplate (/app/node_modules/nunjucks/src/environment.js:130:17)
   at Obj.extend.render (/app/node_modules/nunjucks/src/environment.js:211:14)
   at NunjucksView.render (/app/node_modules/nunjucks/src/environment.js:193:15)
   at EventEmitter.app.render (/app/node_modules/express/lib/application.js:530:10)

**Comment by fuzzyfox** [comment]
This appears to be a typo in the handler dealing with the 404. With that route its likely the default not found handler in `server.js`
